<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <link name="base_link"></link>

    <!-- CHASSIS -->
    <xacro:property name="chassis_mass" value="0.5" />
    <xacro:property name="chassis_width" value="0.3" />
    <xacro:property name="chassis_length" value="0.3" />
    <xacro:property name="chassis_height" value="0.15" />

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="-0.1 0 0" /> <!-- przesuniecie punktu referencyjnego -->

    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_width* 0.5} 0 0${chassis_height * 0.5}" rpy="0 0 0" /> <!-- przesuniecie geometrii od punktu referencyjnego, polowa wymiarow jak rzucisz okiem-->
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <origin xyz="0.15 0 0.075" />
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
        </collision>

        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_width}" y="${chassis_length}" z="${chassis_height}">
            <origin xyz="${chassis_width* 0.5} 0 0${chassis_height * 0.5}" rpy="0 0 0" />
        </xacro:inertial_box>

    </link>

    <!-- gazebo uses different materials/colors than rviz so for correct dispaly requires additional tags -->
    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- WHEELS -->
    <xacro:property name="wheel_mass" value="0.1" />
    <xacro:property name="wheel_length" value="0.04" />
    <xacro:property name="wheel_radius" value="0.05" />

    <!-- LEFT WHEEL -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <!-- zwroc uwage na kÄ…t, zawsze cylindry obracamy tak by z-axis
             wskazywala na zewnatrz, dlatego musimy zaflipowac znaki na osiach -->
        <origin xyz="0 0.175 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="0 -0.175 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="0.05" />
                />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL -->
    <xacro:property name="caster_mass" value="0.1" />
    <xacro:property name="caster_radius" value="0.05" />

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis" />
        <child link="caster_wheel" />
        <origin xyz="0.24 0 0" rpy="0 0 0" />
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_mass}" radius="${caster_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001" />
        <mu2 value="0.001" />
    </gazebo>

</robot>